# Generated by Django 2.2 on 2019-09-11 02:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('misiones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('mision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='misiones.Mision')),
            ],
            options={
                'verbose_name': 'Medición',
                'verbose_name_plural': 'Mediciones',
                'permissions': (('add_Medicion', 'Puede guardar mediciones'), ('view_Medicion', 'Puede ver mediciones'), ('change_Medicion', 'Puede actualizar mediciones'), ('delete_Medicion', 'Puede eliminar mediciones')),
                'default_permissions': (),
            },
        ),
    ]
