# Generated by Django 2.2 on 2019-09-11 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('misiones', '0002_medicion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicion',
            name='mision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='misiones.Mision'),
        ),
    ]
