# Generated by Django 2.2 on 2019-09-12 02:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('misiones', '0003_auto_20190910_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='mision',
            name='comandante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medicion',
            name='mision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='misiones.Mision'),
        ),
    ]
