# Generated by Django 2.2 on 2019-10-01 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('misiones', '0004_auto_20190911_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicion',
            name='mision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mediciones', to='misiones.Mision'),
        ),
    ]
